spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/wechat_shop?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  port: 8080
  servlet:
    context-path: /sell

wechat:
  # 微信测试号的appid和appsecret
  mpAppId: wx22c4e2ae87e0e03b
  mpAppSecret: d045e7f8dc0acb6965e1cd9ece1e99a3

projectUrl:
  wechatMpAuthorize: http://47.94.18.181
  wechatOpenAuthorize: http://47.94.18.181
  sell: http://47.94.18.181

#ftp相关配置
ftp:
  host: 47.94.18.181
  port: 21
  userName: ftpuser
  passWord: 123
  basePath: /home/ftpuser/images
#图片服务器相关配置
  baseUrl: http://47.94.18.181/upload/images